### ISSUE TITLE
failed to build with Visual Studio

### ISSUE THREAD

**Issue by SSE4** [rbock/sqlpp11-connector-stl#3]
fails with the following error:
```
         c:\.conan\oxrcs2xw\1\source_subfolder\include\sqlpp11\container\sort_order.h(53): error C2977: 'sqlpp::sort_order_t': too many template arguments [C:\.conan\oxrcs2xw\1\build_subfolder\source_subfolder\tests\SqlppStlSampleTest.vcxproj]
         c:\.conan\oxrcs2xw\1\source_subfolder\include\sqlpp11\container\sort_order.h(54): error C3203: 'sort_order_t': unspecialized class template can't be used as a template argument for template parameter 'T', expected a real type [C:\.conan\oxrcs2xw\1\build_subfolder\source_subfolder\tests\SqlppStlSampleTest.vcxproj]
         c:\.conan\oxrcs2xw\1\source_subfolder\include\sqlpp11\container\sort_order.h(52): error C3211: 'sqlpp::interpreter_t<sqlpp::container::context_t,int,void>': explicit specialization is using partial specialization syntax, use template <> instead [C:\.conan\oxrcs2xw\1\build_subfolder\source_subfolder\tests\SqlppStlSampleTest.vcxproj]

```

**Comment by rbock** [comment]
Thanks for the hint.

This is rather experimental code that will only really come to fruition if and when there will be compile time reflection including construction like with Metaclasses. Thus it is not regularly tended.

I pushed change to develop that should make it compile again, though (at least it compiles on my machine using clang).

**Comment by SSE4** [comment]
@rbock thanks for the update
it did the trick, just one more minor fix is needed for:
```
expression.h(88): error C2039: 'logical_and': is not a member of 'std'
```
adding the `<functional>` include, and it builds fine.
is it possible to make 0.5 release with these changes?

**Comment by rbock** [comment]
0.5 is tagged and pushed.

Thanks for looking into sqlpp11 in conan, btw., very much appreciated!
