### ISSUE TITLE
[question] why experimental?

### ISSUE THREAD

**Issue by fawdlstty** [rbock/sqlpp11-connector-stl#4]

**Comment by rbock** [comment]
At the time this was created, I did not know if or how I could ever finish it.

It is incomplete and unmaintained.

I believe that once C++ has reflection and generation this would be possible in a decent fashion.

**Comment by fawdlstty** [comment]
How does this project differ from sqlite3 in InMemory mode？

**Comment by rbock** [comment]
sqlite3 InMemory is using sqlite. This is about using any standard library container or stream (or range in C++20) like a database table and run queries on it.
